name: mddo-lab
topology:
    links:
    -   endpoints:
        - a01c.chib:eth1
        - Seg-220.150.196.32-27:Ethernet1
    -   endpoints:
        - g01c.chib:eth1
        - Seg-220.150.196.32-27:Ethernet2
    -   endpoints:
        - g02j.chib:eth1
        - Seg-220.150.196.32-27:Ethernet3
    -   endpoints:
        - r01c.chib:eth1
        - Seg-220.150.196.32-27:Ethernet4
    -   endpoints:
        - r02j.chib:eth1
        - Seg-220.150.196.32-27:Ethernet5
    -   endpoints:
        - a01c.chib:eth2
        - Seg-220.150.196.96-30:Ethernet1
    -   endpoints:
        - a02c.chib:eth1
        - Seg-220.150.196.96-30:Ethernet2
    -   endpoints:
        - a02c.chib:eth2
        - Seg-163.138.255.84-30:Ethernet1
    -   endpoints:
        - a02j.akbu:eth1
        - Seg-163.138.255.84-30:Ethernet2
    -   endpoints:
        - a02c.chib:eth3
        - Seg-220.150.196.64-27:Ethernet1
    -   endpoints:
        - g01c.chib:eth2
        - Seg-220.150.196.64-27:Ethernet2
    -   endpoints:
        - g02j.chib:eth2
        - Seg-220.150.196.64-27:Ethernet3
    -   endpoints:
        - r01c.chib:eth2
        - Seg-220.150.196.64-27:Ethernet4
    -   endpoints:
        - r02j.chib:eth2
        - Seg-220.150.196.64-27:Ethernet5
    -   endpoints:
        - a02j.akbu:eth2
        - Seg-163.138.255.36-30:Ethernet1
    -   endpoints:
        - g01j.akbu:eth1
        - Seg-163.138.255.36-30:Ethernet2
    -   endpoints:
        - a02j.akbu:eth3
        - Seg-163.138.255.44-30:Ethernet1
    -   endpoints:
        - g02j.akbu:eth1
        - Seg-163.138.255.44-30:Ethernet2
    -   endpoints:
        - a02j.akbu:eth4
        - Seg-163.138.255.52-30:Ethernet1
    -   endpoints:
        - g03j.akbu:eth1
        - Seg-163.138.255.52-30:Ethernet2
    -   endpoints:
        - a02j.akbu:eth5
        - Seg-163.138.255.60-30:Ethernet1
    -   endpoints:
        - g04j.akbu:eth1
        - Seg-163.138.255.60-30:Ethernet2
    -   endpoints:
        - a02j.akbu:eth6
        - Seg-163.138.255.64-30:Ethernet1
    -   endpoints:
        - a01j.akbu:eth1
        - Seg-163.138.255.64-30:Ethernet2
    -   endpoints:
        - g04j.akbu:eth2
        - Seg-163.138.255.56-30:Ethernet1
    -   endpoints:
        - a01j.akbu:eth2
        - Seg-163.138.255.56-30:Ethernet2
    -   endpoints:
        - g03j.akbu:eth2
        - Seg-163.138.255.48-30:Ethernet1
    -   endpoints:
        - a01j.akbu:eth3
        - Seg-163.138.255.48-30:Ethernet2
    -   endpoints:
        - g01j.akbu:eth2
        - Seg-163.138.255.32-30:Ethernet1
    -   endpoints:
        - a01j.akbu:eth4
        - Seg-163.138.255.32-30:Ethernet2
    nodes:
        Seg-163.138.255.32-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.32-30.conf
        Seg-163.138.255.36-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.36-30.conf
        Seg-163.138.255.44-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.44-30.conf
        Seg-163.138.255.48-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.48-30.conf
        Seg-163.138.255.52-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.52-30.conf
        Seg-163.138.255.56-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.56-30.conf
        Seg-163.138.255.60-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.60-30.conf
        Seg-163.138.255.64-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.64-30.conf
        Seg-163.138.255.84-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-163.138.255.84-30.conf
        Seg-220.150.196.32-27:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-220.150.196.32-27.conf
        Seg-220.150.196.64-27:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-220.150.196.64-27.conf
        Seg-220.150.196.96-30:
            image: ceos:4.27.3F
            kind: arista_ceos
            startup-config: Seg-220.150.196.96-30.conf
        a01c.chib:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: a01c.chib.conf
        a01j.akbu:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: a01j.akbu.conf
        a02c.chib:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: a02c.chib.conf
        a02j.akbu:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: a02j.akbu.conf
        g01c.chib:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: g01c.chib.conf
        g01j.akbu:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: g01j.akbu.conf
        g02j.akbu:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: g02j.akbu.conf
        g02j.chib:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: g02j.chib.conf
        g03j.akbu:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: g03j.akbu.conf
        g04j.akbu:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: g04j.akbu.conf
        r01c.chib:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: r01c.chib.conf
        r02j.chib:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: r02j.chib.conf
