name: mddo-lab
topology:
    links:
    -   endpoints:
        - regiona-ce01:eth5
        - regiona-acc01:eth1
    -   endpoints:
        - regiona-ce01:eth6
        - regiona-acc01:eth2
    -   endpoints:
        - regiona-ce02:eth5
        - regiona-acc01:eth3
    -   endpoints:
        - regiona-ce02:eth6
        - regiona-acc01:eth4
    -   endpoints:
        - regiona-ce01:eth7
        - regiona-acc01:eth5
    -   endpoints:
        - regiona-ce01:eth8
        - regiona-acc01:eth6
    -   endpoints:
        - regiona-ce02:eth7
        - regiona-acc01:eth7
    -   endpoints:
        - regiona-ce02:eth8
        - regiona-acc01:eth8
    -   endpoints:
        - regiona-svr01:eth1
        - regiona-acc01:eth9
    -   endpoints:
        - regiona-svr01:eth2
        - regiona-acc01:eth10
    -   endpoints:
        - regiona-svr02:eth1
        - regiona-acc01:eth11
    -   endpoints:
        - regiona-svr02:eth2
        - regiona-acc01:eth12
    -   endpoints:
        - regiona-pe02:eth4
        - regiona-ce02:eth2
    -   endpoints:
        - regiona-ce01:eth3
        - regiona-ce02:eth3
    -   endpoints:
        - regiona-ce01:eth4
        - regiona-ce02:eth4
    -   endpoints:
        - regionb-pe02:eth1
        - regiona-pe02:eth1
    -   endpoints:
        - regiona-pe01:eth2
        - regiona-pe02:eth2
    -   endpoints:
        - regionb-pe01:eth1
        - regiona-pe01:eth1
    -   endpoints:
        - regiona-ce01:eth1
        - regiona-pe01:eth3
    -   endpoints:
        - regionb-pe02:eth2
        - regionb-pe01:eth2
    -   endpoints:
        - regionb-ce01:eth1
        - regionb-pe01:eth3
    -   endpoints:
        - regionb-ce02:eth3
        - regionb-ce01:eth3
    -   endpoints:
        - regionb-ce02:eth4
        - regionb-ce01:eth4
    -   endpoints:
        - regionb-acc01:eth1
        - regionb-ce01:eth5
    -   endpoints:
        - regionb-acc01:eth2
        - regionb-ce01:eth6
    -   endpoints:
        - regionb-acc02:eth1
        - regionb-ce01:eth7
    -   endpoints:
        - regionb-acc02:eth2
        - regionb-ce01:eth8
    -   endpoints:
        - regionb-ce02:eth7
        - regionb-acc02:eth3
    -   endpoints:
        - regionb-ce02:eth8
        - regionb-acc02:eth4
    -   endpoints:
        - regionb-svr02:eth1
        - regionb-acc02:eth5
    -   endpoints:
        - regionb-svr02:eth2
        - regionb-acc02:eth6
    -   endpoints:
        - regionb-ce02:eth5
        - regionb-acc01:eth3
    -   endpoints:
        - regionb-ce02:eth6
        - regionb-acc01:eth4
    -   endpoints:
        - regionb-svr01:eth1
        - regionb-acc01:eth5
    -   endpoints:
        - regionb-svr01:eth2
        - regionb-acc01:eth6
    -   endpoints:
        - regionb-pe02:eth4
        - regionb-ce02:eth2
    nodes:
        regiona-acc01:
            image: crpd:22.1R1.10
            kind: crpd
        regiona-ce01:
            image: crpd:22.1R1.10
            kind: crpd
        regiona-ce02:
            image: crpd:22.1R1.10
            kind: crpd
        regiona-pe01:
            image: crpd:22.1R1.10
            kind: crpd
        regiona-pe02:
            image: crpd:22.1R1.10
            kind: crpd
        regiona-svr01:
            image: crpd:22.1R1.10
            kind: crpd
        regiona-svr02:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-acc01:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-acc02:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-ce01:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-ce02:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-pe01:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-pe02:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-svr01:
            image: crpd:22.1R1.10
            kind: crpd
        regionb-svr02:
            image: crpd:22.1R1.10
            kind: crpd

