name: test011
#mgmt:
# network: my-multihost-network
topology:
  nodes:
    ceos1:
      kind: ceos
      image: ceos-lab:4.27.2F
    ceos2:
      kind: ceos
      image: ceos-lab:4.27.2F
    crpd1:
      kind: crpd
      image: crpd:22.1R1.10
#    vmx1:
#      kind: vr-vmx
#      image: vrnetlab/vr-vmx:18.1R1.9

  links:
    - endpoints: ["ceos1:eth1","ceos2:eth1"]
    - endpoints: ["ceos1:eth2","crpd1:eth1"]

