---
- hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
      ansible_connection: ansible.netcommon.network_cli
      ansible_user: vrnetlab
      ansible_password: VR-netlab9
      status_dir: "/tmp/configs/status"


  tasks:
    - name: show interfaces
      ansible.netcommon.cli_command:
        command: show interfaces 
      when: ansible_network_os == 'junos'
      register: command_junos_result

    - name: save status files
      copy:
        content: "{{ command_junos_result.stdout }}"
        dest: "{{ status_dir }}/{{ inventory_hostname }}_show_interfaces.txt"
      when: ansible_network_os == 'junos'
      changed_when: False

    - name: show interfaces 
      ansible.netcommon.cli_command:
        command: show interfaces
      when: ansible_network_os == 'iosxr'
      register: command_ios_result

    - name: save status files
      copy:
        content: "{{ command_ios_result.stdout }}"
        dest: "{{ status_dir }}/{{ inventory_hostname }}_show_interfaces.txt"
      when: ansible_network_os == 'iosxr'
      changed_when: False

    - name: change enable mode 
      ansible.netcommon.cli_command:
        command: enable 
      when: ansible_network_os == 'eos'

    - name: show interfaces
      ansible.netcommon.cli_command:
        command: show interfaces
      when: ansible_network_os == 'eos'
      register: command_eos_result
    
    - name: save status files
      copy:
        content: "{{ command_eos_result.stdout }}"
        dest: "{{ status_dir }}/{{ inventory_hostname }}_show_interfaces.txt"
      when: ansible_network_os == 'eos'
      changed_when: False

- hosts: localhost 
  gather_facts: false
  connection: local
  vars:
      status_dir: "/tmp/configs/status"

  tasks:
    - name: git add & commit & push
      git_acp:
        user: eterny13
        token: mytoken 
        path: "{{ status_dir }}"
        branch: main
        comment: Add status files
        remote: origin
        add: "."
        mode: https
        url: "https://github.com/ool-mddo/pushed_configs.git"
