---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - netbox.netbox

  vars:
    ansible_python_interpreter: /usr/bin/python3
    netbox_url: http://192.168.23.31:8000
    netbox_token: 0123456789abcdef0123456789abcdef01234567

  tasks:
    - name: add host values
      add_host:
        name: "{{ item.value.name }}"
        ansible_host: "{{ item.value.name }}"
        ansible_network_os: "{{ item.value.local_context_data.ansible_network_os }}"
        ansible_user: "{{ item.value.local_context_data.ansible_user }}"
        ansible_password: "{{ item.value.local_context_data.ansible_password }}"
      loop: "{{ query('netbox.netbox.nb_lookup','devices', api_endpoint=netbox_url, token=netbox_token) }}"


- hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
      config_dir: "/tmp/configs/configs"


  tasks:
    - name: show command
      ansible.netcommon.cli_command:
        command: show config
      when: ansible_network_os == 'junos'
      register: command_junos_result

    - name: save config files
      copy:
        content: "{{ command_junos_result.stdout }}"
        dest: "{{ config_dir }}/{{ inventory_hostname }}_config.txt"
      when: ansible_network_os == 'junos'
      changed_when: False

    - name: show command
      ansible.netcommon.cli_command:
        command: show running-config
      when: ansible_network_os == 'iosxr'
      register: command_ios_result

    - name: save config files
      copy:
        content: "{{ command_ios_result.stdout }}"
        dest: "{{ config_dir }}/{{ inventory_hostname }}_config.txt"
      when: ansible_network_os == 'iosxr'
      changed_when: False

    - name: change enable mode 
      ansible.netcommon.cli_command:
        command: enable 
      when: ansible_network_os == 'eos'

    - name: show command
      ansible.netcommon.cli_command:
        command: show running-config 
      when: ansible_network_os == 'eos'
      register: command_eos_result
    
    - name: save config files
      copy:
        content: "{{ command_eos_result.stdout }}"
        dest: "{{ config_dir }}/{{ inventory_hostname }}_config.txt"
      when: ansible_network_os == 'eos'
      changed_when: False

- hosts: localhost 
  gather_facts: false
  connection: local
  vars:
      config_dir: "/tmp/configs/configs"

  tasks:
    - name: git add & commit & push
      git_acp:
        user: eterny13
        token: mytoken
        path: "{{ config_dir }}"
        branch: main
        comment: Add config files
        remote: origin
        add: "."
        mode: https
        url: "https://github.com/ool-mddo/pushed_configs.git"
