name: mddo-lab
topology:
    links:
    -   endpoints:
        - rt1:eth1
        - Seg-203.0.113.0-24:eth1
    -   endpoints:
        - serv1:eth1
        - Seg-203.0.113.0-24:eth2
    -   endpoints:
        - rt1:eth2
        - Seg-10.0.0.0-30:eth1
    -   endpoints:
        - rt2:eth1
        - Seg-10.0.0.0-30:eth2
    -   endpoints:
        - rt1:eth3
        - Seg-10.0.1.0-30:eth1
    -   endpoints:
        - rt3:eth1
        - Seg-10.0.1.0-30:eth2
    -   endpoints:
        - rt3:eth2
        - Seg-10.1.0.0-24:eth1
    -   endpoints:
        - rt2:eth2
        - Seg-10.1.0.0-24:eth2
    -   endpoints:
        - rt4:eth1
        - Seg-10.1.0.0-24:eth3
    -   endpoints:
        - rt4:eth2
        - Seg-192.168.0.0-24:eth1
    -   endpoints:
        - serv2:eth1
        - Seg-192.168.0.0-24:eth2
    nodes:
        Seg-10.0.0.0-30:
            image: ceos-lab:4.27.2F
            kind: arista_ceos
            startup-config: Seg-10.0.0.0-30.conf
        Seg-10.0.1.0-30:
            image: ceos-lab:4.27.2F
            kind: arista_ceos
            startup-config: Seg-10.0.1.0-30.conf
        Seg-10.1.0.0-24:
            image: ceos-lab:4.27.2F
            kind: arista_ceos
            startup-config: Seg-10.1.0.0-24.conf
        Seg-192.168.0.0-24:
            image: ceos-lab:4.27.2F
            kind: arista_ceos
            startup-config: Seg-192.168.0.0-24.conf
        Seg-203.0.113.0-24:
            image: ceos-lab:4.27.2F
            kind: arista_ceos
            startup-config: Seg-203.0.113.0-24.conf
        rt1:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: rt1.conf
        rt2:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: rt2.conf
        rt3:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: rt3.conf
        rt4:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: rt4.conf
        serv1:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: serv1.conf
        serv2:
            image: crpd:22.1R1.10
            kind: juniper_crpd
            startup-config: serv2.conf
