name: mddo-lab
topology:
    links:
    -   endpoints:
        - regiona-ce01:eth1
        - br17230100:veth5733
    -   endpoints:
        - regiona-ce02:eth1
        - br17230100:veth3285
    -   endpoints:
        - regiona-svr01:eth1
        - br17230100:veth7075
    -   endpoints:
        - regiona-svr02:eth1
        - br17230100:veth9867
    -   endpoints:
        - regiona-ce01_vrf1:eth1
        - br172301100:veth7231
    -   endpoints:
        - regiona-ce02_vrf1:eth1
        - br172301100:veth5022
    -   endpoints:
        - regiona-svr01:eth2
        - br172301100:veth7016
    -   endpoints:
        - regiona-svr02:eth2
        - br172301100:veth7942
    -   endpoints:
        - regiona-ce01:eth2
        - br17230200:veth6912
    -   endpoints:
        - regiona-ce02:eth2
        - br17230200:veth6817
    -   endpoints:
        - regiona-ce01_vrf1:eth2
        - br172301200:veth6906
    -   endpoints:
        - regiona-ce02_vrf1:eth2
        - br172301200:veth9748
    -   endpoints:
        - regiona-ce02:eth3
        - br1721640:veth9411
    -   endpoints:
        - regiona-pe02:eth1
        - br1721640:veth1894
    -   endpoints:
        - regiona-ce02:eth4
        - br1721650:veth4123
    -   endpoints:
        - regiona-ce01:eth3
        - br1721650:veth2099
    -   endpoints:
        - regiona-pe02:eth2
        - br10110:veth7262
    -   endpoints:
        - regionb-pe02:eth1
        - br10110:veth6355
    -   endpoints:
        - regiona-pe02:eth3
        - br1721600:veth8467
    -   endpoints:
        - regiona-pe01:eth1
        - br1721600:veth6105
    -   endpoints:
        - regiona-pe01:eth2
        - br10100:veth1863
    -   endpoints:
        - regionb-pe01:eth1
        - br10100:veth5972
    -   endpoints:
        - regiona-pe01:eth3
        - br1721610:veth9049
    -   endpoints:
        - regiona-ce01:eth4
        - br1721610:veth2500
    -   endpoints:
        - regionb-pe01:eth2
        - br1721700:veth6271
    -   endpoints:
        - regionb-pe02:eth2
        - br1721700:veth2473
    -   endpoints:
        - regionb-pe01:eth3
        - br1721710:veth5703
    -   endpoints:
        - regionb-ce01:eth1
        - br1721710:veth5368
    -   endpoints:
        - regionb-ce01:eth2
        - br1721750:veth9492
    -   endpoints:
        - regionb-ce02:eth1
        - br1721750:veth9187
    -   endpoints:
        - regionb-ce01:eth3
        - br17231100:veth2690
    -   endpoints:
        - regionb-ce02:eth2
        - br17231100:veth5853
    -   endpoints:
        - regionb-svr01:eth1
        - br17231100:veth0179
    -   endpoints:
        - regionb-ce01_VR1:eth1
        - br172311100:veth9611
    -   endpoints:
        - regionb-ce02_VR1:eth1
        - br172311100:veth4924
    -   endpoints:
        - regionb-svr01:eth2
        - br172311100:veth9460
    -   endpoints:
        - regionb-ce01:eth4
        - br17231200:veth7280
    -   endpoints:
        - regionb-ce02:eth3
        - br17231200:veth4976
    -   endpoints:
        - regionb-svr02:eth1
        - br17231200:veth2489
    -   endpoints:
        - regionb-ce01_VR1:eth2
        - br172311200:veth5864
    -   endpoints:
        - regionb-ce02_VR1:eth2
        - br172311200:veth5887
    -   endpoints:
        - regionb-svr02:eth2
        - br172311200:veth8469
    -   endpoints:
        - regionb-ce02:eth4
        - br1721740:veth1970
    -   endpoints:
        - regionb-pe02:eth3
        - br1721740:veth4373
    nodes:
        br10100:
            kind: bridge
        br10110:
            kind: bridge
        br1721600:
            kind: bridge
        br1721610:
            kind: bridge
        br1721640:
            kind: bridge
        br1721650:
            kind: bridge
        br1721700:
            kind: bridge
        br1721710:
            kind: bridge
        br1721740:
            kind: bridge
        br1721750:
            kind: bridge
        br17230100:
            kind: bridge
        br172301100:
            kind: bridge
        br172301200:
            kind: bridge
        br17230200:
            kind: bridge
        br17231100:
            kind: bridge
        br172311100:
            kind: bridge
        br172311200:
            kind: bridge
        br17231200:
            kind: bridge
        regiona-ce01:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regiona-ce01_vrf1:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regiona-ce02:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regiona-ce02_vrf1:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regiona-pe01:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regiona-pe02:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regiona-svr01:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regiona-svr02:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-ce01:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-ce01_VR1:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-ce02:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-ce02_VR1:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-pe01:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-pe02:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-svr01:
            image: crpd:22.1R1.10
            kind: juniper_crpd
        regionb-svr02:
            image: crpd:22.1R1.10
            kind: juniper_crpd
