---
- hosts: docker-host
  gather_facts: false
  become: yes
  vars:
    multihost_bridge: "multihost-network"
    ansible_user: "{{ login_user}}"
    ansible_password: "{{ login_pass }}"
    ansible_sudo_pass: "{{ sudo_pass }}"
    ansible_python_interpreter: /usr/bin/python3
    containerlab_basedir: /home/test/
    L1_topo_file: /home/test/pushed_configs/L1_topo/layer1_topology.sample.json
    #multihost_bridge: "my-multihost-network"


  tasks:
    - name: "check {{ multihost_bridge }} network "
      command:
        cmd: "docker network inspect {{ multihost_bridge }}"
      register: docker_network
      failed_when: false

    - name: "check swarm manager node"
      command:
        cmd: "docker node ls"
      register: docker_node
      failed_when: false

    - name: "create {{ multihost_bridge }} for Manager node"
      command:
        cmd: "docker network create -d overlay {{ multihost_bridge }} --attachable"
      when: docker_network.rc != 0 and docker_node.rc == 0

    - name: "create {{ multihost_bridge }} for worker node"
      shell: "docker run --name temp_alpine -itd alpine:latest /bin/sh; docker network connect {{ multihost_bridge }} temp_alpine"
      when: docker_network.rc != 0 and docker_node.rc != 0

