- hosts: Junos
  gather_facts: false
  vars:
    mddo_model_file: "./pushed_configs_mddo_network.json"
    nodes: {}
    containerlab: []
    convertif: []
    nodered_url: "http://192.168.80.2:1880"
  tasks:
#  - name: show config
#    junipernetworks.junos.junos_command:
#      commands: show configuration
#      display: xml

  - name:
    junipernetworks.junos.junos_l3_interfaces:
      running_config: "{{ lookup('file', './rt1.xml') }}"
      state: parsed

