---
- name: add host
  hosts:
    - localhost
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
    netbox_url: http://192.168.23.31:8000
    netbox_token: 0123456789abcdef0123456789abcdef01234567
  tasks:
    - name: add host values
      add_host:
        name: "{{ item.value.display }}"
        ansible_host: "{{ item.value.local_context_data.management_address | default('127.0.0.1') }}"
        ansible_network_os: "{{ item.value.local_context_data.ansible_network_os | default('Ubuntu') }}"
        ansible_user: "{{ item.value.local_context_data.ansible_user | default('test')}}"
        ansible_password: "{{ item.value.local_context_data.ansible_password | default('nopass')}}"
      loop: "{{ query('netbox.netbox.nb_lookup','devices', api_endpoint=netbox_url, token=netbox_token) }}"
