---
- hosts: localhost
  gather_facts: false
  become: yes
  vars:
    mddo_model_file: "./pushed_configs_mddo_network.json"
    links: {}
    nodes: {}
    containerlab: []
    convertif: []
    cnf_image:
      kind: 'crpd'
      image: 'crpd:22.1R1.10'
  tasks:
    - name: 
      set_fact: 
        topology: "{{lookup('file', mddo_model_file) }}"
        
    - name: 
      set_fact:
        topology2: "{{ topology['ietf-network:networks'] | community.general.json_query(query1) }}"
      vars:
        query1: 'network[-3]'

    - set_fact:
        layer3: "{{topology2['node']  | community.general.json_query(query1)}}"
      vars:
        query1: '[*].{"node": "node-id", "l3_if": "ietf-network-topology:termination-point"}'


    - set_fact:
        iflist: |-
          [ 
          {%- for item in layer3 -%}        
            {{ item['l3_if']  | community.general.json_query(query1)}} ,
          {%- endfor -%}
          ]
      vars:
        query1: '[*]."tp-id"'

    - set_fact:
            if_list: "{{ if_list| default([]) + [ { item['node'] : item['l3_if'] | community.general.json_query(query1)   } ] }}"
      vars:
        query1: '[*]."tp-id"'
      loop: "{{ layer3 }}"

    - set_fact: 
        convertif: "{{ convertif + [ tmpdict ]  }}"
      vars:
        tmpdict:
         node: "{{ key[0] }}"
         iflist: "{{ tmp }}"
        key: "{{ item.keys() }}"
        tmp: |-
          [
          {%- for list in  item.values() -%}
          {%- for value in  list -%}
          {%- set current = list.index(value) -%}
          { "{{ value }}": "eth{{ current +1  }}" } ,
          {%- endfor -%}
          {%- endfor -%}
          ] 
      loop: "{{ if_list  }}"

    - name:
      copy:
        dest: "./convert-if.yml"
        content: "{{ convertif | to_nice_yaml }}"

    - name:
      set_fact:
        inout_info: "{{topology2['ietf-network-topology:link']  | community.general.json_query(query1)}}"
      vars:
        query1: '[*].{"dest-node": destination."dest-node", "dest-if": destination."dest-tp", "source-node": source."source-node", "source-if": source."source-tp"}'

    - name:
      set_fact:
        tmp_uniq_list1: "{{ tmp_uniq_list1 |default([]) + [ { key1: 1, key2: 1 } ]  }}"
      vars:
        key1: >-
          {%- for tmpdict in convertif -%}
          {%-   if item['dest-node'] == tmpdict['node'] -%}
          {%-     for key in tmpdict.iflist -%}
          {%-       set ifnamelist = key.keys() -%}
          {%-       for ifname in ifnamelist -%}
          {%-         if ( ifname == item['dest-if'] ) -%}
          {%-           for convertifname in key.values() -%}
          {{ item['dest-node'] | regex_replace('\/', '_' ) }}:{{ convertifname }}
          {%-           endfor -%}
          {%-         endif -%}
          {%-       endfor -%}
          {%-     endfor -%}
          {%-   endif -%}
          {%- endfor -%}
        key2: >-
          {%- for tmpdict in convertif -%}
          {%-   if item['source-node'] == tmpdict['node'] -%}
          {%-     for key in tmpdict.iflist -%}
          {%-       set ifnamelist = key.keys() -%}
          {%-       for ifname in ifnamelist -%}
          {%-         if ( ifname == item['source-if'] ) -%}
          {%-           for convertifname in key.values() -%}
          {{ item['source-node'] | regex_replace('\/', '_' ) }}:{{ convertifname }}
          {%-           endfor -%}
          {%-         endif -%}
          {%-       endfor -%}
          {%-     endfor -%}
          {%-   endif -%}
          {%- endfor -%}
      loop: "{{ inout_info  }}"


    - name:
      set_fact:
        uniq_list: "{{ tmp_uniq_list1 | unique }}"

    - set_fact:
        links: |-
            [
            {%- for dicts in uniq_list  %} 
            {%- set tmplist = dicts.keys() -%}
            {"endpoints":  {{ tmplist }}  },
            {%- endfor %}
            ]

    - set_fact:
        nodes: "{{ nodes | combine( { convert_nodes : cnf_image } ) }}"
      vars:
        convert_nodes: "{{ item['dest-node'] | regex_replace('\/', '_' ) }}" 
      loop: "{{ inout_info }}"

    - set_fact:
        containerlab:
          name: "mddo-lab"
          topology:
            nodes: "{{ nodes }}"
            links: "{{ links }}"

    - name:
      copy:
        dest: "./clab-topo.yml"
        content: "{{ containerlab | to_nice_yaml }}"


