---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: send command
      command: ansible-galaxy collection list
      register: res_collections


- hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
      ansible_network_os: junos
      ansible_connection: ansible.netcommon.network_cli
      ansible_user: vrnetlab
      ansible_password: VR-netlab9


  tasks:
    - name: show command
      ansible.netcommon.cli_command:
        command: show config

