---
- hosts: docker-host
  gather_facts: false
  become: yes
  vars:
    ansible_user: "{{ login_user}}"
    ansible_password: "{{ login_pass }}"
    ansible_sudo_pass: "{{ sudo_pass }}"
    ansible_python_interpreter: /usr/bin/python3
    mddo_containerlab_file: "./clab-topo.yml"
    operation: create
    #operation: delete

  tasks:
    - name:
      set_fact:
        containerlab: "{{lookup('file', mddo_containerlab_file)  | from_yaml }}"

    - debug:
        msg: "{{ item.key }}"
      loop: "{{ containerlab.topology.nodes | dict2items }}"
      when: '"br" in item.key' 

    - command:
        cmd: "ip link add  {{ item.key }} type bridge"
      loop: "{{ containerlab.topology.nodes | dict2items }}"
      when: '"br" in item.key and operation == "create"'

    - name: Creating a file with content
      copy:
        dest: "/tmp/clab-topo.yml"
        content: "{{ containerlab | to_yaml }}"

    - name: deploy containerlab
      command:
        cmd: "containerlab deploy --topo /tmp/clab-topo.yml --reconfigure"
      when: operation == 'create'

    - name: destroy containerlab
      command:
        cmd: "containerlab destroy --topo /tmp/clab-topo.yml"
      when: operation == 'delete'

    - command:
        cmd: "ip link del  {{ item.key }}"
      loop: "{{ containerlab.topology.nodes | dict2items }}"
      when: '"br" in item.key and operation == "delete"'

