---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: create directory
      file: path=/home/kawaguchi/configs state=directory owner=kawaguchi group=kawaguchi mode=0755


- hosts: RegionB-PE01
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
      ansible_network_os: junos
      ansible_connection: ansible.netcommon.network_cli
      ansible_user: vrnetlab
      ansible_password: VR-netlab9

  tasks:
    - name: show command
      ansible.netcommon.cli_command:
        command: show config
      register: command_result
      tags: common

    - name: output config files
      local_action:
        module: copy
        owner: kawaguchi
        group: kawaguchi
        mode: 0644
        dest: "/home/kawaguchi/configs/{{ inventory_hostname }}_config.txt"
        content: "{{ command_result.stdout }}"
      changed_when: False

- hosts: localhost 
  gather_facts: false
  connection: local

  tasks:
    - name: git add & commit & push
      git_acp:
        user: ""
        token: ""
        path: /home/kawaguchi/configs/   # .git/ のディレクトリ
        branch: main            # git push 先のブランチ
        comment: Add junos config file         # git commit -m "Add file" commit のコメント
        add: "." # git add するファイル
        mode: https                 # https/ssh/local のいずれか。httpは対応していません
        url: "https://github.com/ool-mddo/test-git-acp-ansible.git"
